#!/bin/bash

#As an eexample, this will be run inside a dedicated X session, openbox or any light wdw manager may be nedded here for some emulators to receive properly events generated by GAL.
#Custom settings for the X session may be stated here too.

su -l -c [PWD]/gal.py `whoami` &> [PWD]/log.txt
